version: '3.3'
services:
  api:
    container_name: api
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: sandman
      DB_PASS: postgres@123
      DB_NAME: nodedb
    build:
      context: ./
      dockerfile: Dockerfile.dev
      # args:
      #   INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: sandman
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: nodedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
