@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@baseUrl = http://{{host}}/api/v1
@authToken = {{login.response.body.accessToken}}

GET http://{{host}}/

###
GET {{baseUrl}}/health

###
# @name login
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "username": "superuser@example.com",
  "password": "SandMan@123"
}

###
GET {{baseUrl}}/users/
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/users/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "SandMan-2.1",
  "email": "sandman2@example.com",
  "password": "SandMan@123"
}

###
GET {{baseUrl}}/users/<user.id>
Authorization: Bearer {{authToken}}

###
PUT {{baseUrl}}/users/<user.id>
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "SandMan-2.3",
  "email": "sandman2.3@example.com",
  "password": "SandMan@123"
}

###
DELETE  {{baseUrl}}/users/<user.id>
Authorization: Bearer {{authToken}}
